/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;


import Management.SQLConnection;
import Management.Admin;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class AntConsult extends javax.swing.JFrame {
    
    
    

    /**
     * Creates new form consuAntecedentes
     */
    public AntConsult() {
        initComponents();
        setImages();
        this.setLocationRelativeTo(null);
        antecedentesTable.getTableHeader().setUI(null);
        antecedentesTable.setShowVerticalLines(true);
        antecedentesTable.setRowHeight(antecedentesTable.getRowCount()-1, antecedentesTable.getRowHeight(0)*2);
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarB = new javax.swing.JButton();
        regresarB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        antecedentesTable = new javax.swing.JTable();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarB.setText("Editar");
        editarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBActionPerformed(evt);
            }
        });
        getContentPane().add(editarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        regresarB.setText("Regresar");
        regresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBActionPerformed(evt);
            }
        });
        getContentPane().add(regresarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        antecedentesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nombre", null},
                {"Diabetes", null},
                {"Hipertension", null},
                {"Obesidad", null},
                {"Tabaquismo", null},
                {"Alcoholismo", null},
                {"Drogas", ""},
                {"Otro", null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        antecedentesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(antecedentesTable);
        if (antecedentesTable.getColumnModel().getColumnCount() > 0) {
            antecedentesTable.getColumnModel().getColumn(0).setResizable(false);
            antecedentesTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            antecedentesTable.getColumnModel().getColumn(0).setHeaderValue(null);
            antecedentesTable.getColumnModel().getColumn(1).setResizable(false);
            antecedentesTable.getColumnModel().getColumn(1).setPreferredWidth(350);
            antecedentesTable.getColumnModel().getColumn(1).setHeaderValue(null);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 580, 160));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setImages()
    {
        ClassLoader classLoader = this.getClass().getClassLoader();
        ImageIcon image = new ImageIcon(classLoader.getResource("Images/white.jpg"));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_DEFAULT));
        backgroundLabel.setIcon(icon);
    }
    
    private void showTable()
    {
        TodosPacientes tP = new TodosPacientes();
        Connection con = null;
        DefaultTableModel model;
        ResultSet rs;
        try{
            String[] titulos = {"Nombre","Diabetes","Hipertension","Obesidad","Tabaquismo","Alcoholismo","Drogas","Otro"};
            model = new DefaultTableModel(null, titulos);
            String datos[] = new String[8];
            con = SQLConnection.getSQLConnection();
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT datos.Nombre,antecedentes.* from datos INNER JOIN antecedentes ON antecedentes.Id_ante = datos.Id WHERE datos.Id = ?");
            ps.setString(1, tP.getID());
            rs = ps.executeQuery();
           
            while(rs.next()){
                antecedentesTable.setValueAt(rs.getString("Nombre"), 0, 1);
                datos[0]=rs.getString("Nombre");
                
                antecedentesTable.setValueAt(rs.getString("Diabetes"), 1, 1);
                datos[1]=rs.getString("Diabetes");
                
                antecedentesTable.setValueAt(rs.getString("Hipertension"), 2, 1);
                datos[2]=rs.getString("Hipertension");
                
                antecedentesTable.setValueAt(rs.getString("Obesidad"), 3, 1);
                datos[3]=rs.getString("Obesidad");
                
                antecedentesTable.setValueAt(rs.getString("Tabaquismo"), 4, 1);
                datos[4]=rs.getString("Tabaquismo");
                
                antecedentesTable.setValueAt(rs.getString("Alcoholismo"), 5, 1);
                datos[5]=rs.getString("Alcoholismo");
                
                antecedentesTable.setValueAt(rs.getString("Drogas"), 6, 1);
                datos[6]=rs.getString("Drogas");
                
                antecedentesTable.setValueAt(rs.getString("Otro"), 7, 1);
                datos[7]=rs.getString("Otro");
                
                
            }
            antecedentesTable.setDefaultEditor(Object.class, null);

            
            con.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }
    
    
    private void regresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBActionPerformed
        Admin.returnTodosPacientes();
        dispose();
    }//GEN-LAST:event_regresarBActionPerformed

    private void editarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBActionPerformed
        Admin.openAntEdit();
        dispose();
    }//GEN-LAST:event_editarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AntConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AntConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AntConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AntConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AntConsult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable antecedentesTable;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton editarB;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresarB;
    // End of variables declaration//GEN-END:variables
}
