/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;


import Management.SQLConnection;
import Management.Admin;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class DatosConsult extends javax.swing.JFrame {
    
    // Creates new form ConsuDaGe
    public DatosConsult() {
        initComponents();
        setImages();
        datosTable.getTableHeader().setUI(null);
        datosTable.setShowVerticalLines(true);
        datosTable.setRowHeight(datosTable.getRowCount()-1, datosTable.getRowHeight(0)*2);
        showTable();
        this.setLocationRelativeTo(null);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarB = new javax.swing.JButton();
        editarB = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosTable = new javax.swing.JTable();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresarB.setText("Regresar");
        regresarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBActionPerformed(evt);
            }
        });
        getContentPane().add(regresarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        editarB.setText("Editar");
        editarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBActionPerformed(evt);
            }
        });
        getContentPane().add(editarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        datosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nombre", null},
                {"Fecha", null},
                {"Edad", null},
                {"Sexo", null},
                {"Telefono", null},
                {"Correo", null},
                {"Domicilio", null},
                {"Motivo", null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        datosTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(datosTable);
        if (datosTable.getColumnModel().getColumnCount() > 0) {
            datosTable.getColumnModel().getColumn(0).setResizable(false);
            datosTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            datosTable.getColumnModel().getColumn(0).setHeaderValue(null);
            datosTable.getColumnModel().getColumn(1).setResizable(false);
            datosTable.getColumnModel().getColumn(1).setPreferredWidth(350);
            datosTable.getColumnModel().getColumn(1).setHeaderValue(null);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 490, 150));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBActionPerformed
        //Admin.returnTodosPacientes();
        Admin.openTodosPacientes();
        dispose();
    }//GEN-LAST:event_regresarBActionPerformed

    private void editarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBActionPerformed
        Admin.openDatosEdit();
        dispose();
    }//GEN-LAST:event_editarBActionPerformed

    private void setImages()
    {
        ClassLoader classLoader = this.getClass().getClassLoader();
        ImageIcon image = new ImageIcon(classLoader.getResource("Images/white.jpg"));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_DEFAULT));
        backgroundLabel.setIcon(icon);
    }
    
    private void showTable()
    {
        TodosPacientes tP = new TodosPacientes();
        Connection con = null;
        DefaultTableModel model;
        ResultSet rs;
        
        try{
            String[] titulos = {"Nombre","Fecha","Edad","Sexo","Telefono","Correo","Domicilio","Motivo"};
            model = new DefaultTableModel(null, titulos);
            String datos[] = new String[8];
            con = SQLConnection.getSQLConnection();
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT * From datos WHERE Id = ?");
            ps.setString(1, tP.getID());
            
            rs = ps.executeQuery();
            
            while(rs.next()){
                datosTable.setValueAt(rs.getString("Nombre"), 0, 1);
                datos[0]=rs.getString("Nombre");
                datosTable.setValueAt(rs.getString("Fecha"), 1, 1);
                datos[1]=rs.getString("Fecha");
                datosTable.setValueAt(rs.getString("Edad"), 2, 1);
                datos[2]=rs.getString("Edad");
                datosTable.setValueAt(rs.getString("Sexo"), 3, 1);
                datos[3]=rs.getString("Sexo");
                datosTable.setValueAt(rs.getString("Telefono"), 4, 1);
                datos[4]=rs.getString("Telefono");
                datosTable.setValueAt(rs.getString("Correo"), 5, 1);
                datos[5]=rs.getString("Correo");
                datosTable.setValueAt(rs.getString("Domicilio"), 6, 1);
                datos[6]=rs.getString("Domicilio");
                datosTable.setValueAt(rs.getString("Motivo"), 7, 1);
                datos[7]=rs.getString("Motivo");
                
                model.addRow(datos);    
            }
            
            con.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosConsult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTable datosTable;
    private javax.swing.JButton editarB;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresarB;
    // End of variables declaration//GEN-END:variables
}
