/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Management.Admin;
import Management.Messages;
import Management.SQLConnection;
import Management.SQLStatements;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class ExaFisEdit extends javax.swing.JFrame {

    // Attributes
    private static String cardio="";
    private static String respi="";
    private static String gastro="";
    private static String geni="";
    private static String muscu="";
    private static String piel="";
    
    /**
     * Creates new form examenFisico
     */
    public ExaFisEdit() {
        initComponents();
        setImages();
        setActionCommands();
        fillRadioButtons();
        this.repaint();
    }

    
    private void setActionCommands()
    {
        cardioSiRB.setActionCommand("Si");
        cardioNoRB.setActionCommand("No");
        respiSiRB.setActionCommand("Si");
        respiNoRB.setActionCommand("No");
        gastroSiRB.setActionCommand("Si");
        gastroNoRB.setActionCommand("No");
        geniSiRB.setActionCommand("Si");
        geniNoRB.setActionCommand("No");
        muscuSiRB.setActionCommand("Si");
        muscuNoRB.setActionCommand("No");
        pielSiRB.setActionCommand("Si");
        pielNoRB.setActionCommand("No");
    }
    
    //Background Images
    private void setImages()
    {
        ClassLoader classLoader = this.getClass().getClassLoader();
        ImageIcon image = new ImageIcon(classLoader.getResource("Images/white.jpg"));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(backgroundImage.getWidth(), backgroundImage.getHeight(), Image.SCALE_DEFAULT));
        backgroundImage.setIcon(icon);
        
        image = new ImageIcon(classLoader.getResource("Images/backImage.png"));
        icon = new ImageIcon(image.getImage().getScaledInstance(regresarButton.getWidth(), regresarButton.getHeight(), Image.SCALE_DEFAULT));
        regresarButton.setIcon(icon);
        
        image = new ImageIcon(classLoader.getResource("Images/nextImage.png"));
        icon = new ImageIcon(image.getImage().getScaledInstance(siguienteButton.getWidth(), siguienteButton.getHeight(), Image.SCALE_DEFAULT));
        siguienteButton.setIcon(icon);   
    }
    
    
    //Setters
    public static void setCardio(String c) { cardio = c; }
    public static void setRespiratorio(String r) { respi = r; }
    public static void setGastrointestinal(String g) { gastro = g; }
    public static void setGenito(String g) { geni = g; }
    public static void setMusculo(String m) { muscu = m; }
    public static void setPiel(String p) { piel = p; }
    
    //Getters
    public static String getCardio() { return cardio; }
    public static String getRespiratorio() { return respi; }
    public static String getGastrointestinal() { return gastro; }
    public static String getGenito() { return geni; }
    public static String getMusculo() { return muscu; }
    public static String getPiel() { return piel; }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardioBG = new javax.swing.ButtonGroup();
        respiBG = new javax.swing.ButtonGroup();
        gastroBG = new javax.swing.ButtonGroup();
        geniBG = new javax.swing.ButtonGroup();
        muscuBG = new javax.swing.ButtonGroup();
        pielBG = new javax.swing.ButtonGroup();
        lblCardio = new javax.swing.JLabel();
        lblRespi = new javax.swing.JLabel();
        lblGastro = new javax.swing.JLabel();
        lblGeni = new javax.swing.JLabel();
        lblMuscu = new javax.swing.JLabel();
        lblPiel = new javax.swing.JLabel();
        lblCardioNor = new javax.swing.JLabel();
        lblGastroNor = new javax.swing.JLabel();
        lblRespiNor = new javax.swing.JLabel();
        lblMuscuNor = new javax.swing.JLabel();
        lblGeniNor = new javax.swing.JLabel();
        lblPielNor = new javax.swing.JLabel();
        cardioSiRB = new javax.swing.JRadioButton();
        respiSiRB = new javax.swing.JRadioButton();
        gastroSiRB = new javax.swing.JRadioButton();
        geniSiRB = new javax.swing.JRadioButton();
        pielSiRB = new javax.swing.JRadioButton();
        muscuSiRB = new javax.swing.JRadioButton();
        respiNoRB = new javax.swing.JRadioButton();
        cardioNoRB = new javax.swing.JRadioButton();
        gastroNoRB = new javax.swing.JRadioButton();
        geniNoRB = new javax.swing.JRadioButton();
        pielNoRB = new javax.swing.JRadioButton();
        muscuNoRB = new javax.swing.JRadioButton();
        examenLabel = new javax.swing.JLabel();
        siguienteButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCardio.setText("Cardiovascular");
        getContentPane().add(lblCardio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblRespi.setText("Respiratorio");
        getContentPane().add(lblRespi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblGastro.setText("Gastrointestinal");
        getContentPane().add(lblGastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblGeni.setText("Genito-urinario");
        getContentPane().add(lblGeni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblMuscu.setText("Músculo-esquelético");
        getContentPane().add(lblMuscu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblPiel.setText("Piel");
        getContentPane().add(lblPiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        lblCardioNor.setText("(Normal)");
        getContentPane().add(lblCardioNor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        lblGastroNor.setText("(Normal)");
        getContentPane().add(lblGastroNor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        lblRespiNor.setText("(Normal)");
        getContentPane().add(lblRespiNor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        lblMuscuNor.setText("(Normal)");
        getContentPane().add(lblMuscuNor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        lblGeniNor.setText("(Normal)");
        getContentPane().add(lblGeniNor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        lblPielNor.setText("(Normal)");
        getContentPane().add(lblPielNor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        cardioBG.add(cardioSiRB);
        cardioSiRB.setText("Sí");
        cardioSiRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cardioSiRBMouseReleased(evt);
            }
        });
        getContentPane().add(cardioSiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        respiBG.add(respiSiRB);
        respiSiRB.setText("Sí");
        respiSiRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                respiSiRBMouseReleased(evt);
            }
        });
        getContentPane().add(respiSiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        gastroBG.add(gastroSiRB);
        gastroSiRB.setText("Sí");
        gastroSiRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gastroSiRBMouseReleased(evt);
            }
        });
        getContentPane().add(gastroSiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        geniBG.add(geniSiRB);
        geniSiRB.setText("Sí");
        geniSiRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                geniSiRBMouseReleased(evt);
            }
        });
        getContentPane().add(geniSiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        pielBG.add(pielSiRB);
        pielSiRB.setText("Sí");
        pielSiRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pielSiRBMouseReleased(evt);
            }
        });
        getContentPane().add(pielSiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        muscuBG.add(muscuSiRB);
        muscuSiRB.setText("Sí");
        muscuSiRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                muscuSiRBMouseReleased(evt);
            }
        });
        getContentPane().add(muscuSiRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        respiBG.add(respiNoRB);
        respiNoRB.setText("No");
        respiNoRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                respiNoRBMouseReleased(evt);
            }
        });
        getContentPane().add(respiNoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        cardioBG.add(cardioNoRB);
        cardioNoRB.setText("No");
        cardioNoRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cardioNoRBMouseReleased(evt);
            }
        });
        getContentPane().add(cardioNoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        gastroBG.add(gastroNoRB);
        gastroNoRB.setText("No");
        gastroNoRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gastroNoRBMouseReleased(evt);
            }
        });
        getContentPane().add(gastroNoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        geniBG.add(geniNoRB);
        geniNoRB.setText("No");
        geniNoRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                geniNoRBMouseReleased(evt);
            }
        });
        getContentPane().add(geniNoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        pielBG.add(pielNoRB);
        pielNoRB.setText("No");
        pielNoRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pielNoRBMouseReleased(evt);
            }
        });
        getContentPane().add(pielNoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        muscuBG.add(muscuNoRB);
        muscuNoRB.setText("No");
        muscuNoRB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                muscuNoRBMouseReleased(evt);
            }
        });
        getContentPane().add(muscuNoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        examenLabel.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        examenLabel.setText("Examen físico");
        getContentPane().add(examenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, 50));

        siguienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nextImage.png"))); // NOI18N
        siguienteButton.setBorder(null);
        siguienteButton.setBorderPainted(false);
        siguienteButton.setContentAreaFilled(false);
        siguienteButton.setEnabled(false);
        siguienteButton.setFocusPainted(false);
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(siguienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 70, 20));

        regresarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/backImage.png"))); // NOI18N
        regresarButton.setBorder(null);
        regresarButton.setBorderPainted(false);
        regresarButton.setContentAreaFilled(false);
        regresarButton.setFocusPainted(false);
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 70, 20));

        jLabel1.setText("TA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel2.setText("FC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 50, -1));

        jLabel3.setText("FR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 50, -1));

        jLabel4.setText("T");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 10, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 50, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###/###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 50, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 680, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    public static void enableBtnSiguiente()
    {
        if((cardioSiRB.isSelected() || cardioNoRB.isSelected()) &&
                (respiSiRB.isSelected() || respiNoRB.isSelected()) &&
                (gastroSiRB.isSelected() || gastroNoRB.isSelected()) &&
                (geniSiRB.isSelected() || geniNoRB.isSelected()) &&
                (muscuSiRB.isSelected() || muscuNoRB.isSelected()) &&
                (pielSiRB.isSelected() || pielNoRB.isSelected()))
        {
            siguienteButton.setEnabled(true);
        }
        else
        {
            siguienteButton.setEnabled(false);
        }
    }
    
    private void setGetters()
    {
        cardio = cardioBG.getSelection().getActionCommand();
        respi = respiBG.getSelection().getActionCommand();
        gastro = gastroBG.getSelection().getActionCommand();
        geni = geniBG.getSelection().getActionCommand();
        muscu = muscuBG.getSelection().getActionCommand();
        piel = pielBG.getSelection().getActionCommand();
    }
    
    public static void fillRadioButtons()
    {
        Connection con = null;
        con = SQLConnection.getSQLConnection();
        ResultSet rs;
        String datos[] = new String[6];
        TodosPacientes tP = new TodosPacientes();
        try{
        PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT examen_fisico.* from examen_fisico WHERE examen_fisico.Id_exFi = ?");
        ps.setString(1, tP.getID());
        rs = ps.executeQuery();
        while(rs.next()){         
             datos[0]=rs.getString("Cardiovascular");
             datos[1]=rs.getString("Respiratorio");
             datos[2]=rs.getString("Gastrointestinal");
             datos[3]=rs.getString("Genito_urinario");
             datos[4]=rs.getString("Musculo_esqueletico");
             datos[5]=rs.getString("Piel");
        }
        con.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
        if("Si".equals(datos[0])) { cardioSiRB.setSelected(true); }
        else { cardioNoRB.setSelected(true); }
        if("Si".equals(datos[1])) { respiSiRB.setSelected(true); }
        else { respiNoRB.setSelected(true); }
        if("Si".equals(datos[2])) { gastroSiRB.setSelected(true); }
        else { gastroNoRB.setSelected(true); }
        if("Si".equals(datos[3])) { geniSiRB.setSelected(true); }
        else { geniNoRB.setSelected(true); }
        if("Si".equals(datos[4])) { muscuSiRB.setSelected(true); }
        else { muscuNoRB.setSelected(true); }
        if("Si".equals(datos[5])) { pielSiRB.setSelected(true); }
        else { pielNoRB.setSelected(true); }
    }
    
    
    //siguienteButton
    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed
        setGetters();
        Messages message = new Messages();
        String table = "examen_fisico";
        String[] values = new String[] {
            cardio,respi,gastro,geni,muscu,piel
        };
        SQLStatements statement = new SQLStatements();
        if(statement.update(table,values))
            message.informationMessage("Datos actualizados", "Datos actualizados con éxito");
        else
            message.errorMesage("Error", "Ha ocurrido un error al actualizar los datos");
        Admin.openConsuExaFi();
        dispose();
    }//GEN-LAST:event_siguienteButtonActionPerformed

    
    //BOTÓN PARA IR A ANTECEDENTES
    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        Admin.returnAntecedentes();
        dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    
    private void cardioSiRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardioSiRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_cardioSiRBMouseReleased

    private void cardioNoRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardioNoRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_cardioNoRBMouseReleased

    private void respiSiRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respiSiRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_respiSiRBMouseReleased

    private void respiNoRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_respiNoRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_respiNoRBMouseReleased

    private void gastroSiRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastroSiRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_gastroSiRBMouseReleased

    private void gastroNoRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastroNoRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_gastroNoRBMouseReleased

    private void geniSiRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geniSiRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_geniSiRBMouseReleased

    private void geniNoRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geniNoRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_geniNoRBMouseReleased

    private void muscuSiRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muscuSiRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_muscuSiRBMouseReleased

    private void muscuNoRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muscuNoRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_muscuNoRBMouseReleased

    private void pielSiRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pielSiRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_pielSiRBMouseReleased

    private void pielNoRBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pielNoRBMouseReleased
        enableBtnSiguiente();
    }//GEN-LAST:event_pielNoRBMouseReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExaFisEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExaFisEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExaFisEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExaFisEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExaFisEdit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.ButtonGroup cardioBG;
    private static javax.swing.JRadioButton cardioNoRB;
    private static javax.swing.JRadioButton cardioSiRB;
    private javax.swing.JLabel examenLabel;
    private javax.swing.ButtonGroup gastroBG;
    private static javax.swing.JRadioButton gastroNoRB;
    private static javax.swing.JRadioButton gastroSiRB;
    private javax.swing.ButtonGroup geniBG;
    private static javax.swing.JRadioButton geniNoRB;
    private static javax.swing.JRadioButton geniSiRB;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblCardio;
    private javax.swing.JLabel lblCardioNor;
    private javax.swing.JLabel lblGastro;
    private javax.swing.JLabel lblGastroNor;
    private javax.swing.JLabel lblGeni;
    private javax.swing.JLabel lblGeniNor;
    private javax.swing.JLabel lblMuscu;
    private javax.swing.JLabel lblMuscuNor;
    private javax.swing.JLabel lblPiel;
    private javax.swing.JLabel lblPielNor;
    private javax.swing.JLabel lblRespi;
    private javax.swing.JLabel lblRespiNor;
    private javax.swing.ButtonGroup muscuBG;
    private static javax.swing.JRadioButton muscuNoRB;
    private static javax.swing.JRadioButton muscuSiRB;
    private javax.swing.ButtonGroup pielBG;
    private static javax.swing.JRadioButton pielNoRB;
    private static javax.swing.JRadioButton pielSiRB;
    private javax.swing.JButton regresarButton;
    private javax.swing.ButtonGroup respiBG;
    private static javax.swing.JRadioButton respiNoRB;
    private static javax.swing.JRadioButton respiSiRB;
    private static javax.swing.JButton siguienteButton;
    // End of variables declaration//GEN-END:variables
}
