/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;


import Management.SQLConnection;
import Management.Admin;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ExaFisConsult extends javax.swing.JFrame {

    
    
    /**
     * Creates new form consuExaFi
     */
    public ExaFisConsult() {
        initComponents();
        setImages();
        this.setLocationRelativeTo(null);
        fisicoTable.getTableHeader().setUI(null);
        fisicoTable.setShowVerticalLines(true);
        //fisicoTable.setRowHeight(fisicoTable.getRowCount()-1, fisicoTable.getRowHeight(0)*2);
        showTable();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarButton = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fisicoTable = new javax.swing.JTable();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        fisicoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Nombre", null},
                {"Cardiovascular", null},
                {"Respiratorio", null},
                {"Gastrointestinal", null},
                {"Genito_urinario", null},
                {"Musculo_esqueletico", null},
                {"Piel", null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fisicoTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(fisicoTable);
        if (fisicoTable.getColumnModel().getColumnCount() > 0) {
            fisicoTable.getColumnModel().getColumn(0).setResizable(false);
            fisicoTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            fisicoTable.getColumnModel().getColumn(0).setHeaderValue(null);
            fisicoTable.getColumnModel().getColumn(1).setResizable(false);
            fisicoTable.getColumnModel().getColumn(1).setPreferredWidth(300);
            fisicoTable.getColumnModel().getColumn(1).setHeaderValue(null);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 490, 140));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setImages()
    {
        ClassLoader classLoader = this.getClass().getClassLoader();
        ImageIcon image = new ImageIcon(classLoader.getResource("Images/white.jpg"));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_DEFAULT));
        backgroundLabel.setIcon(icon);
    }
    
    public void showTable()
    {
        Connection con;
        TodosPacientes tP = new TodosPacientes();
        DefaultTableModel model;
        ResultSet rs;
        try{
            //String[] titulos = {"Nombre","Cardiovascular","Respiratorio","Gastrointestinal","Genito_urinario","Musculo_esqueletico","Piel"};
            //model = new DefaultTableModel(null, titulos);
            String titulos[] = new String[7];
            String datos[] = new String[7];
            con = SQLConnection.getSQLConnection();
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT datos.Nombre,examen_fisico.* from datos INNER JOIN examen_fisico ON examen_fisico.Id_exFi = datos.Id WHERE datos.Id = ?");
            ps.setString(1, tP.getID());
            
            
            rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
            String name;
            
            while(rs.next())
            {
                
            for(int i=1; i<=columnCount; i++)
            {
                name = rsmd.getColumnName(i);
                if(i<2)
                {
                   fisicoTable.setValueAt(rs.getString(name), i-1, 1);
                   datos[i-1] = rs.getString(name); 
                   titulos[i-1] = name;
                }
                if(i>2)
                {
                   fisicoTable.setValueAt(rs.getString(name), i-2, 1);
                   datos[i-2] = rs.getString(name); 
                   titulos[i-2] = name;
                }
                
            }
            model = new DefaultTableModel(null, titulos);
            model.addRow(datos);
            }
            
            /*while(rs.next()){
                fisicoTable.setValueAt(rs.getString("Nombre"), 0, 1);
                datos[0]=rs.getString("Nombre");
                
                fisicoTable.setValueAt(rs.getString("Cardiovascular"), 1, 1);
                datos[1]=rs.getString("Cardiovascular");
                
                fisicoTable.setValueAt(rs.getString("Respiratorio"), 2, 1);
                datos[2]=rs.getString("Respiratorio");
                
                fisicoTable.setValueAt(rs.getString("Gastrointestinal"), 3, 1);
                datos[3]=rs.getString("Gastrointestinal");
                
                fisicoTable.setValueAt(rs.getString("Genito_urinario"), 4, 1);
                datos[4]=rs.getString("Genito_urinario");
                
                fisicoTable.setValueAt(rs.getString("Musculo_esqueletico"), 5, 1);
                datos[5]=rs.getString("Musculo_esqueletico");
                
                fisicoTable.setValueAt(rs.getString("Piel"), 6, 1);
                datos[6]=rs.getString("Piel");
                
                model.addRow(datos);
                
            }*/
            //tblExFi.setModel(model);
            //tblExFi.setDefaultEditor(Object.class, null);

            

           
            con.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }
    
    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        Admin.returnTodosPacientes();
        dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        Admin.openExaFisEdit();
        dispose();
    }//GEN-LAST:event_editarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExaFisConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExaFisConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExaFisConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExaFisConsult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExaFisConsult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JTable fisicoTable;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
}
