/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;


import Management.SQLConnection;
import Management.Admin;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class ExaNeu2Consult extends javax.swing.JFrame {

    //Creates new form ConExaNeu2
    public ExaNeu2Consult() {
        initComponents();
        exNeTbl.getTableHeader().setUI(null);
        exNeTbl.setShowVerticalLines(true);
        this.setLocationRelativeTo(null);
        showTable();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        exNeTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        exNeTbl2 = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        regresarButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exNeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {":", null},
                {"I", null},
                {"II", null},
                {"III", null},
                {"IV", null},
                {"V", null},
                {"VI", null},
                {"VII", null},
                {"VIII", null},
                {"IX", null},
                {"X", null},
                {"XII", null},
                {"XII", null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exNeTbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(exNeTbl);
        if (exNeTbl.getColumnModel().getColumnCount() > 0) {
            exNeTbl.getColumnModel().getColumn(0).setResizable(false);
            exNeTbl.getColumnModel().getColumn(0).setHeaderValue(null);
            exNeTbl.getColumnModel().getColumn(1).setResizable(false);
            exNeTbl.getColumnModel().getColumn(1).setHeaderValue(null);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 223, 250));

        exNeTbl2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"MTD", null, null, null, null},
                {"MTI", null, null, null, null},
                {"MPD", null, null, null, null},
                {"MPI", null, null, null, null},
                {"Atávicos", null, null, null, null},
                {"Marcha", null, null, null, null},
                {"Nistagmo", null, null, null, null},
                {"Dismetria", null, null, null, null}
            },
            new String [] {
                "", "Fuerza", "Tono", "Trofismo", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        exNeTbl2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(exNeTbl2);
        if (exNeTbl2.getColumnModel().getColumnCount() > 0) {
            exNeTbl2.getColumnModel().getColumn(0).setResizable(false);
            exNeTbl2.getColumnModel().getColumn(1).setResizable(false);
            exNeTbl2.getColumnModel().getColumn(2).setResizable(false);
            exNeTbl2.getColumnModel().getColumn(3).setResizable(false);
            exNeTbl2.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 389, 180));
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 11, 51, 21));

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regresarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jButton1.setText("Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        siguienteButton.setText("Siguiente");
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(siguienteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        Admin.returnTodosPacientes();
        dispose();
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Admin.openConsuExaNe();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed
        Admin.openConExaNeu3();
        dispose();
    }//GEN-LAST:event_siguienteButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Admin.openExaNeu2Edit();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void showTable() {
        Connection con;
        TodosPacientes tP = new TodosPacientes();
        DefaultTableModel model;
        ResultSet rs;
        try {
            String[] titulos = {"Title 1", "Title 2"};
            model = new DefaultTableModel(null, titulos);
            String datos[] = new String[32];
            con = SQLConnection.getSQLConnection();
            //PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT tabla_mike.Nombre,examen_neurologico.* from tabla_mike INNER JOIN examen_neurologico ON examen_neurologico.Id_exNe = tabla_mike.Id WHERE tabla_mike.Nombre = ?");
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("SELECT datos.Nombre,exnetablas1.* from datos INNER JOIN exnetablas1 ON exnetablas1.Id_Tabla1 = datos.Id WHERE datos.Id = ?");
            ps.setString(1, tP.getID());

            rs = ps.executeQuery();

            while (rs.next()) {
                nombreLabel.setText(rs.getString("Nombre"));
                exNeTbl.setValueAt(rs.getString("FIRST"), 0, 1);
                exNeTbl.setValueAt(rs.getString("I"), 1, 1);
                exNeTbl.setValueAt(rs.getString("II"), 2, 1);
                exNeTbl.setValueAt(rs.getString("III"), 3, 1);
                exNeTbl.setValueAt(rs.getString("IV"), 4, 1);
                exNeTbl.setValueAt(rs.getString("V"), 5, 1);
                exNeTbl.setValueAt(rs.getString("VI"), 6, 1);
                exNeTbl.setValueAt(rs.getString("VII"), 7, 1);
                exNeTbl.setValueAt(rs.getString("VIII"), 8, 1);
                exNeTbl.setValueAt(rs.getString("IX"), 9, 1);
                exNeTbl.setValueAt(rs.getString("X"), 10, 1);
                exNeTbl.setValueAt(rs.getString("XI"), 11, 1);
                exNeTbl.setValueAt(rs.getString("XII"), 12, 1);
            }

            PreparedStatement ts = (PreparedStatement) con.prepareStatement("SELECT exnetablas2.* from datos INNER JOIN exnetablas2 ON exnetablas2.Id_Tabla2 = datos.Id WHERE datos.Id = ?");
            ts.setString(1, tP.getID());
            rs = ts.executeQuery();

            while (rs.next()) {
                int j = 0;
                for (int i = 1; i < 5; i++) {
                    datos[j] = rs.getString("MTD").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("MTI").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("MPD").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("MPI").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("Atavicos").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("Marcha").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("Nistagmo").split("\\,")[i - 1];
                    j++;
                    datos[j] = rs.getString("Dismetria").split("\\,")[i - 1];
                    j++;
                }
            }
            for (int i = 0; i < 32; i++) {
                if(null != datos[i])
                switch (datos[i]) {
                    case "Right":
                        datos[i] = "→";
                        break;
                    case "Left":
                        datos[i] = "←";
                        break;
                    case "Down":
                        datos[i] = "↓";
                        break;
                    case "Up":
                        datos[i] = "↑";
                        break;
                }
            }
            int l = 0;
            for (int j = 1; j < 5; j++) {
                for (int k = 0; k < 8; k++) {
                    if(!datos[l].equals("null"))
                    {
                        exNeTbl2.setValueAt(datos[l], k, j);
                    }
                    l++;
                }
            }
            con.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExaNeu2Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExaNeu2Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExaNeu2Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExaNeu2Consult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExaNeu2Consult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTable exNeTbl;
    private javax.swing.JTable exNeTbl2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton regresarButton;
    private javax.swing.JButton siguienteButton;
    // End of variables declaration//GEN-END:variables
}
