/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import Management.Admin;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */
public class Menu extends javax.swing.JFrame {

    // Creates new form newMenu
    public Menu() {
        initComponents();
        setImages();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rLabel = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();
        consultarButton = new javax.swing.JButton();
        agregarButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        laboratorioButton = new javax.swing.JButton();
        logoLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/addImage.png"))); // NOI18N
        rLabel.setText("R");
        getContentPane().add(rLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 20, 20));

        cLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nextImage.png"))); // NOI18N
        cLabel.setText("C");
        getContentPane().add(cLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 20, 20));

        consultarButton.setText("Consultar");
        consultarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(consultarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 130, 40));

        agregarButton.setText("Registrar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, 40));

        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        laboratorioButton.setText("Laboratorio");
        laboratorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laboratorioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(laboratorioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 130, -1));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoImage.PNG"))); // NOI18N
        logoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 440, 200));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/white.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 520, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Background images
    private void setImages()
    {
        ClassLoader classLoader = this.getClass().getClassLoader();
        ImageIcon image = new ImageIcon(classLoader.getResource("Images/logoImage.PNG"));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(logoLabel.getWidth(), logoLabel.getHeight(), Image.SCALE_DEFAULT));
        logoLabel.setIcon(icon);
        
        image = new ImageIcon(classLoader.getResource("Images/white.jpg"));
        icon = new ImageIcon(image.getImage().getScaledInstance(backgroundLabel.getWidth(), backgroundLabel.getHeight(), Image.SCALE_DEFAULT));
        backgroundLabel.setIcon(icon);
        
        image = new ImageIcon(classLoader.getResource("Images/addImage.png"));
        icon = new ImageIcon(image.getImage().getScaledInstance(rLabel.getWidth(), rLabel.getHeight(), Image.SCALE_DEFAULT));
        rLabel.setIcon(icon);
        
        /*image = new ImageIcon(classLoader.getResource("Images/eye.png"));
        icon = new ImageIcon(image.getImage().getScaledInstance(cLabel.getWidth(), cLabel.getHeight(), Image.SCALE_DEFAULT));
        cLabel.setIcon(icon);*/
    }
    
    //agregarButton
    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        /*Admin.openTodosPacientes();
        dispose();*/
        Admin.openDatos();
        dispose();
    }//GEN-LAST:event_agregarButtonActionPerformed

    //salirButton
    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed

    //laboratorioButton
    private void laboratorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laboratorioButtonActionPerformed
        Admin.openLaboratorio();
        dispose();
    }//GEN-LAST:event_laboratorioButtonActionPerformed

    private void consultarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarButtonActionPerformed
        Admin.openTodosPacientes();
        dispose();
    }//GEN-LAST:event_consultarButtonActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel cLabel;
    private javax.swing.JButton consultarButton;
    private javax.swing.JButton laboratorioButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel rLabel;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
